name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: Yarn-packages-${{ hashFiles('yarn.lock') }}

      - name: Install Yarn dependencies
        run: yarn

      - name: Check types
        run: yarn type-check

      - name: Lint source code
        run: yarn lint

      - name: Run tests
        run: yarn test
